from ..waseda.char import WasedaChar
from ..waseda.space import CharSpace
from ..waseda.a import CharA
from ..waseda.i import CharI
from ..waseda.u import CharU
from ..waseda.e import CharE
from ..waseda.o import CharO
from ..waseda.ka import CharKa
from ..waseda.ki import CharKi
from ..waseda.ku import CharKu
from ..waseda.ke import CharKe
from ..waseda.ko import CharKo
from ..waseda.sa import CharSa
from ..waseda.shi import CharShi
from ..waseda.su import CharSu
from ..waseda.se import CharSe
from ..waseda.so import CharSo
from ..waseda.ta import CharTa
from ..waseda.chi import CharChi
from ..waseda.tsu import CharTsu
from ..waseda.te import CharTe
from ..waseda.to import CharTo
from ..waseda.na import CharNa
from ..waseda.ni import CharNi
from ..waseda.nu import CharNu
from ..waseda.ne import CharNe
from ..waseda.no import CharNo
from ..waseda.ha import CharHa
from ..waseda.hi import CharHi
from ..waseda.hu import CharHu
from ..waseda.he import CharHe
from ..waseda.ho import CharHo
from ..waseda.ma import CharMa
from ..waseda.mi import CharMi
from ..waseda.mu import CharMu
from ..waseda.me import CharMe
from ..waseda.mo import CharMo
from ..waseda.ya import CharYa
from ..waseda.yu import CharYu
from ..waseda.yo import CharYo
from ..waseda.ra import CharRa
from ..waseda.ri import CharRi
from ..waseda.ru import CharRu
from ..waseda.re import CharRe
from ..waseda.ro import CharRo
from ..waseda.wa import CharWa
from ..waseda.an import CharAn
from ..waseda.in_ import CharIn
from ..waseda.un import CharUn
from ..waseda.en import CharEn
from ..waseda.on import CharOn
from ..waseda.kan import CharKan
from ..waseda.kin import CharKin
from ..waseda.kun import CharKun
from ..waseda.ken import CharKen
from ..waseda.kon import CharKon
from ..waseda.san import CharSan
from ..waseda.shin import CharShin
from ..waseda.sun import CharSun
from ..waseda.sen import CharSen
from ..waseda.so import CharSon
from ..waseda.ta import CharTan
from ..waseda.chi import CharChin
from ..waseda.tsu import CharTsun
from ..waseda.te import CharTen
from ..waseda.to import CharTon
from ..waseda.na import CharNan
from ..waseda.ni import CharNin
from ..waseda.nu import CharNun
from ..waseda.ne import CharNen
from ..waseda.no import CharNon
from ..waseda.ha import CharHan
from ..waseda.hi import CharHin
from ..waseda.hu import CharHun
from ..waseda.he import CharHen
from ..waseda.ho import CharHon
from ..waseda.ma import CharMan
from ..waseda.mi import CharMin
from ..waseda.mu import CharMun
from ..waseda.me import CharMen
from ..waseda.mo import CharMon
from ..waseda.ya import CharYan
from ..waseda.yu import CharYun
from ..waseda.yo import CharYon
from ..waseda.ra import CharRan
from ..waseda.ri import CharRin
from ..waseda.ru import CharRun
