from ..waseda.char import WasedaChar
from ..waseda.space import CharSpace
from ..waseda.a import CharA
from ..waseda.i import CharI
from ..waseda.u import CharU
from ..waseda.e import CharE
from ..waseda.o import CharO
from ..waseda.ka import CharKa
from ..waseda.ki import CharKi
from ..waseda.ku import CharKu
from ..waseda.ke import CharKe
from ..waseda.ko import CharKo
from ..waseda.sa import CharSa
from ..waseda.shi import CharShi
from ..waseda.su import CharSu
from ..waseda.se import CharSe
from ..waseda.so import CharSo
from ..waseda.ta import CharTa
from ..waseda.chi import CharChi
from ..waseda.tsu import CharTsu
from ..waseda.te import CharTe
from ..waseda.to import CharTo
from ..waseda.na import CharNa
from ..waseda.ni import CharNi
from ..waseda.nu import CharNu
from ..waseda.ne import CharNe
from ..waseda.no import CharNo
from ..waseda.ha import CharHa
from ..waseda.hi import CharHi
from ..waseda.hu import CharHu
from ..waseda.he import CharHe
from ..waseda.ho import CharHo
from ..waseda.ma import CharMa
from ..waseda.mi import CharMi
from ..waseda.mu import CharMu
from ..waseda.me import CharMe
from ..waseda.mo import CharMo
from ..waseda.ya import CharYa
from ..waseda.yu import CharYu
from ..waseda.yo import CharYo
from ..waseda.ra import CharRa
from ..waseda.ri import CharRi
from ..waseda.ru import CharRu
from ..waseda.re import CharRe
from ..waseda.ro import CharRo
from ..waseda.wa import CharWa
from ..waseda.an import CharAn
from ..waseda.in_ import CharIn
from ..waseda.un import CharUn
