from ..shugiin.char import ShugiinChar
from ..shugiin.space import CharSpace
from ..shugiin.a import CharA
from ..shugiin.ka import CharKa
from ..shugiin.sa import CharSa
from ..shugiin.ta import CharTa
from ..shugiin.na import CharNa
from ..shugiin.ha import CharHa
from ..shugiin.ma import CharMa
from ..shugiin.ya import CharYa
from ..shugiin.ra import CharRa
from ..shugiin.wa import CharWa
from ..shugiin.yama import CharYama
from ..shugiin.wo import CharWo
from ..shugiin.no import JoshiNo
